Repository abadr99/G1_8bit_MCUs_Drivers, pull requests merged in 2023-07, with the labels that each got.

#1 [AVR] : Add GPIO driver part1
  C/Makefile
  C/build.dir
  C/common/Config.h
  C/common/Registes.h
  C/common/Types.h
  C/common/Utils.h
  C/main.c
  C/mcal/GPIO/GPIO.c
  C/mcal/GPIO/GPIO.h
  C/mcal/GPIO/GPIOPrivate.h
  C/mcal/GPIO/README.md
Labels: avr, build

#2 Fix warnings
  C/.gitignore
  C/Makefile
  C/common/Config.h
  C/common/Registes.h
  C/main.c
Labels: build

#6 Configure the GPIO for AVR/PIC [Refat , Noran, Badr]
  C/common/Config.h
  C/common/Registes.h
  C/common/Types.h
  C/common/Utils.h
  C/main.c
  C/mcal/GPIO/GPIO.c
  C/mcal/GPIO/GPIO.h
  C/mcal/GPIO/GPIOPrivate.h
Labels: enhancement, avr, pic, mcal

#8 Ignore vscode file
  .gitignore
  C/.gitignore
Labels: build

#9 Introduce Support For github Pipeline
  .github/workflows/c-cpp.yml
  .github/workflows/configure.sh
  C/common/Types.h
Labels: build

#11 Add Led Driver
  C/build.dir
  C/common/Types.h
  C/hal/LED/LED.c
  C/hal/LED/LED.h
  C/main.c
  C/mcal/GPIO/GPIO.h
Labels: hal

#13 add Buzzer Driver [@Noura,@ABadr]
  C/build.dir
  C/hal/Buzzer/Buzzer.c
  C/hal/Buzzer/Buzzer.h
  C/main.c
Labels: hal

#15 Improve CI system (Badr)
  .github/workflows/c-cpp.yml
  .github/workflows/clean.sh
Labels: build, CI

#14 Introduce style checking to CI
  .github/workflows/c-cpp.yml
  .github/workflows/configure.sh
  C/Makefile
  C/build.dir
  C/common/Config.h
  C/common/Registes.h
  C/common/Types.h
  C/common/Utils.h
  C/hal/LED/LED.c
  C/hal/LED/LED.h
  C/main.c
  C/mcal/GPIO/GPIO.c
  C/mcal/GPIO/GPIO.h
  C/mcal/GPIO/GPIOPrivate.h
  scripts/style-checking/rules-scripts/scripts/rules/B001.tcl
  scripts/style-checking/rules-scripts/scripts/rules/B002.tcl
  scripts/style-checking/rules-scripts/scripts/rules/B003.tcl
  scripts/style-checking/rules-scripts/scripts/rules/CMakeLists.txt
  scripts/style-checking/rules-scripts/scripts/rules/DUMP.tcl
  scripts/style-checking/rules-scripts/scripts/rules/F001.tcl
  scripts/style-checking/rules-scripts/scripts/rules/F002.tcl
  scripts/style-checking/rules-scripts/scripts/rules/L001.tcl
  scripts/style-checking/rules-scripts/scripts/rules/L002.tcl
  scripts/style-checking/rules-scripts/scripts/rules/L003.tcl
  scripts/style-checking/rules-scripts/scripts/rules/L004.tcl
  scripts/style-checking/rules-scripts/scripts/rules/L005.tcl
  scripts/style-checking/rules-scripts/scripts/rules/L006.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T001.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T002.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T003.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T004.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T005.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T006.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T007.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T008.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T009.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T010.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T011.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T012.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T013.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T014.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T015.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T016.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T017.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T018.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T019.tcl
  scripts/style-checking/style-check.sh
Labels: build, CI

#16 Fix issues in style check
  C/Makefile
  scripts/style-checking/rules-scripts/scripts/rules/B003.tcl
  scripts/style-checking/style-check.sh
Labels: build

#18 fix function get bit
  C/common/Utils.h
Labels: bug, mcal

#19 fix style checking errors
  C/common/Config.h
  C/common/Registes.h
  C/common/Types.h
  C/common/Utils.h
  C/hal/Buzzer/Buzzer.c
  C/hal/Buzzer/Buzzer.h
  C/hal/LED/LED.c
  C/hal/LED/LED.h
  C/main.c
  C/mcal/GPIO/GPIO.c
  C/mcal/GPIO/GPIO.h
  C/mcal/GPIO/GPIOPrivate.h
  scripts/style-checking/style-check.sh
Labels: build

#20 Support more style-checking rules (Badr)
  .github/workflows/c-cpp.yml
  .github/workflows/clean.sh
  .github/workflows/configure.sh
  .github/workflows/setupVera.sh
  C/Makefile
  scripts/style-checking/extractDef.py
  scripts/style-checking/rules-description.txt
  scripts/style-checking/rules-scripts/scripts/rules/B002.tcl
  scripts/style-checking/rules-scripts/scripts/rules/B003.tcl
  scripts/style-checking/rules-scripts/scripts/rules/B004.tcl
  scripts/style-checking/rules-scripts/scripts/rules/T003.tcl
  scripts/style-checking/style-check.sh
Labels: build
